### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Listener must not be null

### ISSUE THREAD

**Issue by EsmaeelNabil** [mumayank/AirLocation#9] opened 2019-11-13 17:54 UTC
Fatal Exception: java.lang.NullPointerException
Listener must not be null

**Comment by EsmaeelNabil** [comment] 2019-11-13 17:55
Fatal Exception: java.lang.NullPointerException: Listener must not be null
       at com.google.android.gms.common.internal.Preconditions.checkNotNull(:11)
       at com.google.android.gms.common.api.internal.ListenerHolders.createListenerHolder(:13)
       at com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(:14)
       at mumayank.com.airlocationlibrary.AirLocation$getLocation$1.onSuccess(AirLocation.kt:161)
       at mumayank.com.airlocationlibrary.AirLocation$getLocation$1.onSuccess(AirLocation.kt:22)
       at com.google.android.gms.tasks.zzn.run(:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by mumayank** [comment] 2019-11-15 06:00
Please provide your implementation code example for me to understand this better.

**Comment by mumayank** [comment] 2020-05-08 05:12
Since there were no replies, closing this issue. Not reproducing on my system. This is most probably an issue with the user's implementation of the lib. I request all to read the documentation provided to not miss any steps.

**Closed as completed by mumayank** 2020-05-08 05:12 UTC
