### ISSUE TITLE
Not getting location callback for the first time

### ISSUE THREAD

**Issue by bharathgrandhe-utu** [mumayank/AirLocation#10] opened 2019-11-14 02:35 UTC
After user allowed the permission, location callback is not happening.

**Comment by mumayank** [comment] 2019-11-15 05:59
I request you to provide more details with code example so that I can understand this in details. Currently, I have very little to process anything. I will have to close this issue otherwise.

**Comment by NizarETH** [comment] 2020-03-12 14:30
Me too, only the first time I'm not getting the location, after that the library works fine

**Comment by ArisChoice** [comment] 2020-03-31 08:02
This is not going to on success when  i restart app after allowing required permissions
```

 airLocation = AirLocation(this, true, true, object : AirLocation.Callbacks {
            override fun onSuccess(location: Location) {
                // location fetched successfully, proceed with it
                val latLng = LatLng(location.latitude, location.longitude)
                mDefaultLocation= latLng
                Log.e("onSuccess"," LOCATION PERMISSION GRANTED  ")
            }

            override fun onFailed(locationFailedEnum: AirLocation.LocationFailedEnum) {
                // couldn't fetch location due to reason available in locationFailedEnum
                // you may optionally do something to inform the user, even though the reason may be obvious
                Log.e("onFailed"," LOCATION PERMISSION FAILED  ")
            }

        })

```

**Comment by abryden** [comment] 2020-04-09 16:13
@ArisChoice and others I am guessing you have not included the following code in your activity.

```

 // override and call airLocation object's method by the same name
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        airLocation.onActivityResult(requestCode, resultCode, data);
    }

    // override and call airLocation object's method by the same name
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        airLocation.onRequestPermissionsResult(requestCode, permissions, grantResults);

    }
```

**Closed as completed** 2020-04-17 11:43 UTC

**Comment by abdalla19977** [comment] 2020-07-10 16:04
why u closed the issue while it is present

**Comment by abdalla19977** [comment] 2020-07-10 16:06
why u closed the issue while it is still present

**Comment by mumayank** [comment] 2020-07-10 17:00
I am not able to reproduce it on any of my devices/ emulators. Also, the issue being reported contradicts something that's very core of the library usage description. Lastly, no information has been provided on the device being used, OS version, etc. And the most important thing of all: if this was really an issue, only 3 people may not have reported it, especially when 214+ people took the time to star it.
